...@overview
input.key.class: file-new
app.ui.class: ours-new
app.init.class: ours-todo
app.agents.therapist.class: ours-todo
app.agents.closure.class: ours-todo
app.agents.routine.class: ours-todo
app.agents.honesty.class: ours-todo
external.gemini.class: ext-todo
external.duckduckgo.class: ext-todo
