...@../../_tools/theme
shape: sequence_diagram

assessment_agent: Assessment 에이전트 { class: ours }
gpt4o: GPT-4o { class: ext }
action_agent: Action 에이전트 { class: ours }

assessment_agent -> gpt4o: 본문 지시
gpt4o -> assessment_agent: Assessment 최종 본문
assessment_agent -> action_agent: 이관
action_agent -> gpt4o: 본문 지시
gpt4o -> action_agent: Action 최종 본문
