...@overview
user.class: person
app.main.class: ours
app.run.class: ours-new
app.json.class: ours-new
app.finder.class: ours
app.contact.class: ours-todo
app.research.class: ours-todo
app.writer.class: ours-todo
db.class: store
openai.class: ext-new
exa.class: ext-new
agno.class: ext-todo
