from crewai import Agent, Task, Crew
from crewai_tools import SerperDevTool
import gradio as gr
from langchain_google_genai import ChatGoogleGenerativeAI
import google.generativeai as genai
from PIL import Image as PILImage
import tempfile

def analyze_medical_image(api_key, image):
    if not api_key or image is None:
        return "Please provide API key and medical image"

    try:
        genai.configure(api_key=api_key)

        # Save and process image
        with tempfile.NamedTemporaryFile(delete=False, suffix='.png') as tmp_file:
            if isinstance(image, str):
                img = PILImage.open(image)
            else:
                img = image

            # Resize if needed
            width, height = img.size
            aspect_ratio = width / height
            new_width = 500
            new_height = int(new_width / aspect_ratio)
            resized_image = img.resize((new_width, new_height))
            resized_image.save(tmp_file.name)
            temp_path = tmp_file.name

        # Use Gemini for medical image analysis
        model = genai.GenerativeModel('gemini-2.0-flash-exp')
        img_obj = PILImage.open(temp_path)

        query = """
You are a highly skilled medical imaging expert with extensive knowledge in radiology and diagnostic imaging. Analyze this medical image and structure your response as follows:

### 1. Image Type & Region
- Specify imaging modality (X-ray/MRI/CT/Ultrasound/etc.)
- Identify the anatomical region and positioning
- Comment on image quality and technical adequacy

### 2. Key Findings
- List primary observations systematically
- Note any abnormalities with precise descriptions
- Include measurements and densities where relevant
- Describe location, size, shape, and characteristics
- Rate severity: Normal/Mild/Moderate/Severe

### 3. Diagnostic Assessment
- Provide primary diagnosis with confidence level
- List differential diagnoses in order of likelihood
- Support each diagnosis with observed evidence
- Note any critical or urgent findings

### 4. Patient-Friendly Explanation
- Explain the findings in simple, clear language
- Avoid medical jargon or provide clear definitions
- Include visual analogies if helpful
- Address common patient concerns

### 5. Research Context
- Mention similar medical conditions or cases
- Reference standard treatment protocols
- Include relevant medical information

Format your response using clear markdown headers and bullet points. Be concise yet thorough.
"""

        response = model.generate_content([query, img_obj])

        result = f"""# Medical Imaging Analysis Results

{response.text}

---

**Note**: This analysis is generated by AI and should be reviewed by a qualified healthcare professional.

**DISCLAIMER**: This tool is for educational and informational purposes only. All analyses should be reviewed by qualified healthcare professionals. Do not make medical decisions based solely on this analysis.
"""

        return result

    except Exception as e:
        return f"Error: {str(e)}"

def create_app():
    with gr.Blocks(title="Medical Imaging Diagnosis Agent") as app:
        gr.Markdown("# Medical Imaging Diagnosis Agent")
        gr.Markdown("Upload a medical image for professional AI-powered analysis")

        gr.Markdown("""
        **DISCLAIMER**: This tool is for educational and informational purposes only.
        All analyses should be reviewed by qualified healthcare professionals.
        Do not make medical decisions based solely on this analysis.
        """)

        with gr.Row():
            with gr.Column():
                api_key = gr.Textbox(
                    label="Google API Key",
                    type="password",
                    placeholder="Enter your Google API Key"
                )
                gr.Markdown("[Get your API key](https://aistudio.google.com/apikey)")

                image_input = gr.Image(
                    label="Upload Medical Image",
                    type="pil"
                )

                analyze_btn = gr.Button("Analyze Image", variant="primary")

        with gr.Row():
            output = gr.Markdown(label="Analysis Results")

        analyze_btn.click(
            fn=analyze_medical_image,
            inputs=[api_key, image_input],
            outputs=output
        )

    return app

if __name__ == "__main__":
    app = create_app()
    app.launch()
