...@overview
app.ui.class: ours-new
app.researcher.class: ours-todo
app.planner.class: ours-todo
backend.openai.class: ext-todo
backend.ollama.class: ext-todo
serpapi.class: ext-todo
ics.class: file-todo
