...@overview
user.class: person-todo
app.front.form.class: ours-todo
app.front.main.class: ours-todo
app.data.categories.class: ours-new
app.data.templates.class: ours-new
app.data.config.class: ours-new
app.data.company.class: ours-new
app.flow.run.class: ours-todo
app.flow.finder.class: ours-todo
app.flow.contact.class: ours-todo
app.flow.researcher.class: ours-todo
app.flow.creator.class: ours-todo
db.class: store-todo
openai.class: ext-todo
exa.class: ext-todo
agno.class: ext-todo
