...@overview
app.entry.main.class: ours-new
app.entry.agent.class: ours-todo
app.tools.read_file.class: ours-new
app.tools.write_file.class: ours-new
app.tools.delete_file.class: ours-new
app.tools.web_request.class: ours-new
app.tools.execute_shell.class: ours-new
llm.class: ext-todo
disk.class: store-new
