...@overview
user.class: person-new
app.entry.main.class: ours-todo
app.entry.agent.class: ours-todo
app.gov.wrapper.class: ours-new
app.gov.approval.class: ours-new
app.tools.read_file.class: ours-todo
app.tools.write_file.class: ours-todo
app.tools.delete_file.class: ours-todo
app.tools.web_request.class: ours-todo
app.tools.execute_shell.class: ours-todo
llm.class: ext-todo
disk.class: store-todo
