...@overview
user.class: person-todo
app.entry.main.class: ours-todo
app.entry.agent.class: ours-todo
app.entry.yaml.class: file-todo
app.gov.wrapper.class: ours-todo
app.gov.approval.class: ours-todo
app.pe.engine.class: ours-todo
app.pe.fs.class: ours-new
app.pe.net.class: ours-new
app.pe.rate.class: ours-todo
app.pe.appr.class: ours-todo
app.pe.audit.class: store-todo
app.tools.read_file.class: ours-todo
app.tools.write_file.class: ours-todo
app.tools.delete_file.class: ours-todo
app.tools.web_request.class: ours-todo
app.tools.execute_shell.class: ours-todo
llm.class: ext-todo
disk.class: store-todo
