...@overview
app.logic.finder.class: ours-todo
app.logic.exa_agent.class: ours-new
app.logic.extractor.class: ours-todo
app.logic.report.class: ours-todo
app.logic.analysis.class: ours-new
app.logic.idle.class: ours-new
perplexity.class: ext-todo
exa.class: ext-todo
firecrawl.class: ext-todo
sites.class: ext-todo
openai.class: ext-todo
agno_api.class: ext-todo
