...@overview
user.class: person-new
app.front.ui.class: ours-new
app.front.session.class: store-new
app.logic.finder.class: ours-todo
app.logic.exa_agent.class: ours-todo
app.logic.extractor.class: ours-todo
app.logic.report.class: ours-todo
app.logic.analysis.class: ours-todo
app.logic.idle.class: ours-todo
perplexity.class: ext-todo
exa.class: ext-todo
firecrawl.class: ext-todo
sites.class: ext-todo
openai.class: ext-todo
agno_api.class: ext-todo
