...@overview
prep.reqs.class: file-new
paths.hosted.class: ours-todo
paths.openai.class: ext-todo
paths.local.class: ours-todo
paths.ollama.class: ours-todo
work.tool.class: ours-todo
work.arxiv.class: ext-todo
work.pdf.class: file-todo
