...@overview
reqs.class: file-new
paths.hosted.class: ours-todo
paths.openai.class: ext-todo
paths.local.class: ours-todo
paths.ollama.class: ext-todo
tool.class: ours-todo
arxiv.class: ext-todo
pdf.class: file-todo
