...@overview
local.app.class: ours-new
local.store.class: store-new
external.embed_api.class: ext-new
external.chat_api.class: ext-new
auth.cred.class: file-todo
auth.token.class: file-todo
external.google.class: ext-todo
external.gmail.class: ext-todo
