...@overview
logic.sources.class: file-todo
logic.agent.class: ours-todo
providers.chat_model.class: ext-todo
logic.knowledge.class: ours-new
storage.class: store-new
providers.embed_model.class: ext-new
