...@overview
user.class: person-todo
plane.class: ext-todo
key.class: file-new
app.os.class: ours-todo
app.team.class: ours-todo
app.web.class: ours-new
app.fin.class: ours-todo
app.ddgt.class: ours-new
app.yft.class: ours-todo
app.db.class: store-new
openai.class: ext-new
ddg.class: ext-new
yahoo.class: ext-todo
agno_api.class: ext-todo
